remove unneeded function

diff --git a/mailnotify b/mailnotify
--- a/mailnotify
+++ b/mailnotify
@@ -11,11 +11,6 @@ print_usage() {
     '
 }
 
-malformed_args() {
-    echo "$0: error: malformed arguments." >&2; echo
-    print_usage
-}
-
 datetime_formatted() {
     echo "[$(date +'%Y-%m-%d %H:%M:%S')]"
 }
@@ -41,7 +36,8 @@ done
 
 if ! [ $# -eq 1 ] || echo "$1" | grep -q '^-'; then
     # Error if there is not exactly one parameter or if it starts with "-"
-    malformed_args
+    echo "$0: error: malformed arguments." >&2; echo
+    print_usage
     exit 1
 fi
 
